# Builder stage
FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# Final stage - Scratch
FROM scratch
COPY --from=builder /app/main /main
EXPOSE 8080
CMD ["/main"]
